services:
  - type: web
    name: poemswift
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_PUBLIC_URL
        value: mongodb://mongo:mjiEWicKFBeSAGQxViJaZqZnalWGrmSp@autorack.proxy.rlwy.net:12602
      - key: JWT_SECRET
        generateValue: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
